// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.browser.newtabpage.activity-stream.discoverystream.enabled", true);
user_pref("app.normandy.user_id", "ac124041-3d76-46fa-93f7-b695aba7de52");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 2101);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1574559507);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 86);
user_pref("browser.newtabpage.activity-stream.impressionId", "{05ba565d-6cdf-4030-884d-f4751279eea1}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1574559510595");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1574563110595");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1574559509");
user_pref("browser.slowStartup.averageTime", 9657);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20191002192408");
user_pref("browser.startup.homepage_override.mstone", "69.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1574559509);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1574559510563");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "69.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "56c6b45bb0684baca3e070f31ba984b8");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "69.0.2");
user_pref("extensions.lastPlatformVersion", "69.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"21b09a1b-3b7a-432a-8f68-dc5ccb1e0df1\",\"fxmonitor@mozilla.org\":\"66c8ea62-00f2-4dc7-9750-c53f7b1af3e9\",\"screenshots@mozilla.org\":\"2e03702c-81fa-48c4-aa1e-1674b2ba8263\",\"webcompat-reporter@mozilla.org\":\"cd333284-3354-4b85-9bae-b54236319050\",\"webcompat@mozilla.org\":\"e6b43445-8d09-4b2c-ac09-6d9e042001de\",\"default-theme@mozilla.org\":\"ee57cabd-5b39-47f7-ae35-9e391259cc0f\",\"google@search.mozilla.org\":\"01f13cff-0cde-4111-ab76-22769adf5741\",\"amazondotcom@search.mozilla.org\":\"fd2b1943-112c-47fe-9004-86293dfaaa96\",\"bing@search.mozilla.org\":\"8152e6bb-2d77-41d8-b300-2e3feb0e6dac\",\"ddg@search.mozilla.org\":\"d1e8f1ca-246c-4e40-8e10-c8c0733b7d85\",\"ebay@search.mozilla.org\":\"191db9fd-e1ea-4fe9-abe8-2f469af15c5e\",\"twitter@search.mozilla.org\":\"cefc6851-c1df-46b6-83ff-30a158da3f16\",\"wikipedia@search.mozilla.org\":\"9b43c00c-70ab-4211-a18e-f5eb021b88cb\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "dd3e8262-c6a3-4b73-b16f-579fd30dcf2d");
user_pref("security.sandbox.plugin.tempDirSuffix", "1889986c-8342-4f13-8898-d3f521af2117");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1574559500);
user_pref("toolkit.telemetry.cachedClientID", "b534f996-dc90-40d5-a276-15ed5a0e412b");
user_pref("toolkit.telemetry.previousBuildID", "20191002192408");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
